# -*- mode: ruby -*-
# vi: set ft=ruby :

# Freebsd config
Vagrant.configure("2") do |config|
  config.vm.guest = :freebsd
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
  # config.vm.box = "freebsd/FreeBSD-11.0-CURRENT"
  config.vm.box_url = "https://wunki.org/files/freebsd-10.2-amd64-wunki.box"
  config.vm.box = "freebsd-10.2-amd64-wunki"
  config.ssh.shell = "sh"
  config.vm.base_mac = "080027D14C66"
  config.vm.hostname = "kodos"
  config.vm.network "public_network"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
  end

  config.vm.provision "shell", inline: <<-SHELL
      sudo env ASSUME_ALWAYS_YES=YES pkg update -f 
      sudo env ASSUME_ALWAYS_YES=YES pkg install go
    SHELL

end