# -*- mode: ruby -*-
# vi: set ft=ruby :

# Freebsd config
Vagrant.configure("2") do |config|
  config.vm.guest = :freebsd
  # config.vm.network "forwarded_port", guest: 22, host:2222, host_ip: "0.0.0.0"
  # config.vm.network "public_network", type: "dhcp", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.network "private_network", ip: "10.0.1.11"
  config.vm.synced_folder "../src", "/vagrant", :nfs => true, id: "vagrant-root"
  config.nfs.map_uid = Process.uid
  config.nfs.map_gid = Process.gid

  # config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", type: "rsync" ,disabled: false
  # config.vm.box = "freebsd/FreeBSD-11.0-CURRENT"
  config.vm.box_url = "https://wunki.org/files/freebsd-10.2-amd64-wunki.box"
  config.vm.box = "freebsd-10.2-amd64-wunki"
  config.ssh.shell = "sh"
  # config.vm.base_mac = "080027D14C66"
  config.vm.hostname = "kang"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
  end

  config.vm.provision "shell", inline: <<-SHELL
      sudo env ASSUME_ALWAYS_YES=YES pkg update -f 
      sudo env ASSUME_ALWAYS_YES=YES pkg add -f http://pkg.freebsd.org/freebsd:10:x86:64/latest/All/go-1.7.1,1.txz
      sudo kldload dtraceall
    SHELL

end